name = "prueba-map-japan-api"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Neon database connection string is provided via secret:
# wrangler secret put DATABASE_URL
