-- DATA-03. Generated by drizzle-kit; the three UPDATEs are hand-added.
-- Existing rows with an out-of-range (or NaN) coordinate cannot be shown on a
-- map anyway; clear BOTH coordinates of such a row (a pin needs both) so the
-- CHECK constraints can be added fully validated. Rows with NULL or in-range
-- coordinates are untouched.
UPDATE "activities" SET "lat" = NULL, "lng" = NULL WHERE NOT ("lat" BETWEEN -90 AND 90) OR NOT ("lng" BETWEEN -180 AND 180);--> statement-breakpoint
UPDATE "destinations" SET "lat" = NULL, "lng" = NULL WHERE NOT ("lat" BETWEEN -90 AND 90) OR NOT ("lng" BETWEEN -180 AND 180);--> statement-breakpoint
UPDATE "hotels" SET "lat" = NULL, "lng" = NULL WHERE NOT ("lat" BETWEEN -90 AND 90) OR NOT ("lng" BETWEEN -180 AND 180);--> statement-breakpoint
ALTER TABLE "activities" ADD CONSTRAINT "activities_lat_lng_range" CHECK ("activities"."lat" BETWEEN -90 AND 90 AND "activities"."lng" BETWEEN -180 AND 180);--> statement-breakpoint
ALTER TABLE "destinations" ADD CONSTRAINT "destinations_lat_lng_range" CHECK ("destinations"."lat" BETWEEN -90 AND 90 AND "destinations"."lng" BETWEEN -180 AND 180);--> statement-breakpoint
ALTER TABLE "hotels" ADD CONSTRAINT "hotels_lat_lng_range" CHECK ("hotels"."lat" BETWEEN -90 AND 90 AND "hotels"."lng" BETWEEN -180 AND 180);
