-- Generated by drizzle-kit; the DELETE is hand-added.
-- Concurrent hotel PUTs (delete-then-insert) could leave several hotels for one
-- destination. Keep the newest (highest id = last write) and drop the rest so
-- the unique index can be created.
DELETE FROM "hotels" h USING "hotels" newer WHERE newer."destination_id" = h."destination_id" AND newer."id" > h."id";--> statement-breakpoint
CREATE UNIQUE INDEX "hotels_destination_id_idx" ON "hotels" USING btree ("destination_id");
